//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Akka;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;


namespace Demo.Messages
{
    
    public class CreateAccount : ICommand
    {
        public String Name { get; private set; }//;
        public String Email { get; private set; }//;
        public CreateAccount(String name, String email)
        {
            this.Name = name;
            this.Email = email;
        }
        public virtual CreateAccount SetProperties(String name = default(String), String email = default(String))
        {
            String localName = name;
            if ((name == default(String)))
            {
                localName = this.Name;
            }
            String localEmail = email;
            if ((email == default(String)))
            {
                localEmail = this.Email;
            }
            return new CreateAccount(localName, localEmail);
        }
    }
    public class AccountCreated : IEvent, IIndexAccounts
    {
        public Guid UserId { get; private set; }//;
        public String Name { get; private set; }//;
        public String Email { get; private set; }//;
        public DateTime UtcGenerationDate { get; private set; }//;
        public AccountCreated(Guid userId, String name, String email)
        {
            this.UserId = userId;
            this.Name = name;
            this.Email = email;
            this.UtcGenerationDate = SystemClock.UtcNow;
        }
        public virtual AccountCreated SetProperties(Guid userId = default(Guid), String name = default(String), String email = default(String))
        {
            Guid localUserId = userId;
            if ((userId == default(Guid)))
            {
                localUserId = this.UserId;
            }
            String localName = name;
            if ((name == default(String)))
            {
                localName = this.Name;
            }
            String localEmail = email;
            if ((email == default(String)))
            {
                localEmail = this.Email;
            }
            return new AccountCreated(localUserId, localName, localEmail);
        }
    }
    public class RemoveAccount : ICommand
    {
        public Guid UserId { get; private set; }//;
        public RemoveAccount(Guid userId)
        {
            this.UserId = userId;
        }
        public virtual RemoveAccount SetProperties(Guid userId = default(Guid))
        {
            Guid localUserId = userId;
            if ((userId == default(Guid)))
            {
                localUserId = this.UserId;
            }
            return new RemoveAccount(localUserId);
        }
    }
    public class AccountRemoved : IEvent, IIndexAccounts
    {
        public Guid UserId { get; private set; }//;
        public DateTime UtcGenerationDate { get; private set; }//;
        public AccountRemoved(Guid userId)
        {
            this.UserId = userId;
            this.UtcGenerationDate = SystemClock.UtcNow;
        }
        public virtual AccountRemoved SetProperties(Guid userId = default(Guid))
        {
            Guid localUserId = userId;
            if ((userId == default(Guid)))
            {
                localUserId = this.UserId;
            }
            return new AccountRemoved(localUserId);
        }
    }
    public class AddFriend : ICommand
    {
        public Guid UserId { get; private set; }//;
        public Guid FriendId { get; private set; }//;
        public AddFriend(Guid userId, Guid friendId)
        {
            this.UserId = userId;
            this.FriendId = friendId;
        }
        public virtual AddFriend SetProperties(Guid userId = default(Guid), Guid friendId = default(Guid))
        {
            Guid localUserId = userId;
            if ((userId == default(Guid)))
            {
                localUserId = this.UserId;
            }
            Guid localFriendId = friendId;
            if ((friendId == default(Guid)))
            {
                localFriendId = this.FriendId;
            }
            return new AddFriend(localUserId, localFriendId);
        }
    }
    public class FriendAdded : IEvent
    {
        public Guid UserId { get; private set; }//;
        public Guid FriendId { get; private set; }//;
        public DateTime UtcGenerationDate { get; private set; }//;
        public FriendAdded(Guid userId, Guid friendId)
        {
            this.UserId = userId;
            this.FriendId = friendId;
            this.UtcGenerationDate = SystemClock.UtcNow;
        }
        public virtual FriendAdded SetProperties(Guid userId = default(Guid), Guid friendId = default(Guid))
        {
            Guid localUserId = userId;
            if ((userId == default(Guid)))
            {
                localUserId = this.UserId;
            }
            Guid localFriendId = friendId;
            if ((friendId == default(Guid)))
            {
                localFriendId = this.FriendId;
            }
            return new FriendAdded(localUserId, localFriendId);
        }
    }
}
