//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Akka;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;


namespace Demo.State
{
    using Demo.Messages;
    
    public abstract class AccountStateSubscription : IStateHandler
    {
        public virtual bool Receive(object message)
        {
            return message.Match().With<AccountCreated>(When).With<AccountRemoved>(When).With<FriendAdded>(When).WasHandled;
        }
        protected abstract void When(AccountCreated message);
        protected abstract void When(AccountRemoved message);
        protected abstract void When(FriendAdded message);
    }
}
