//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Akka;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;


namespace Demo.Indexing.Account.Entities
{
    
    public class AccountIndexEntry
    {
public Guid UserId { get; set; }
public String Name { get; set; }
public String Email { get; set; }

    }
}
