//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Akka;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;


namespace Demo.Indexing.Account.State
{
    using Demo.Indexing.Account.Messages;
    
    public interface IAccountIndexStore
    {
        void When(StoreAccount message);
        void When(DeleteAccount message);
    }
    public abstract class IndexSubscription : IStateHandler, IAccountIndexStore
    {
        public virtual bool Receive(object message)
        {
            return message.Match().With<StoreAccount>(When).With<DeleteAccount>(When).WasHandled;
        }
        public abstract void When(StoreAccount message);
        public abstract void When(DeleteAccount message);
    }
}
